############################################
# Makefile for Long Paper
############################################

all:
	pdflatex PidSpectraVsMultLong
	bibtex PidSpectraVsMultLong
	pdflatex PidSpectraVsMultLong
	pdflatex PidSpectraVsMultLong

clean:
	rm -rf *.aux *.log *.blg *.out PidSpectraVsMultLong.pdf *~

