/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as FitsRouteImport } from './routes/fits'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const FitsRoute = FitsRouteImport.update({
  id: '/fits',
  path: '/fits',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/evidence': typeof EvidenceRoute
  '/fits': typeof FitsRoute
  '/literature': typeof LiteratureRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/evidence': typeof EvidenceRoute
  '/fits': typeof FitsRoute
  '/literature': typeof LiteratureRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/evidence': typeof EvidenceRoute
  '/fits': typeof FitsRoute
  '/literature': typeof LiteratureRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents' | '/evidence' | '/fits' | '/literature' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/evidence' | '/fits' | '/literature' | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/evidence'
    | '/fits'
    | '/literature'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  EvidenceRoute: typeof EvidenceRoute
  FitsRoute: typeof FitsRoute
  LiteratureRoute: typeof LiteratureRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fits': {
      id: '/fits'
      path: '/fits'
      fullPath: '/fits'
      preLoaderRoute: typeof FitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  EvidenceRoute: EvidenceRoute,
  FitsRoute: FitsRoute,
  LiteratureRoute: LiteratureRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
